#ifndef NUMC_VERSION_H
#define NUMC_VERSION_H

/**
 * @file version.h
 * @brief numc library version information.
 *
 * This header is generated by CMake from version.h.in.
 * Do not edit manually.
 */

#define NUMC_VERSION_MAJOR 0
#define NUMC_VERSION_MINOR 1
#define NUMC_VERSION_PATCH 0

#define NUMC_VERSION_STRING "0.1.0"

#endif /* NUMC_VERSION_H */
