# CMake generated Testfile for 
# Source directory: /home/rizki/Projects/numc/tests
# Build directory: /home/rizki/Projects/numc/build_test/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ctx]=] "/home/rizki/Projects/numc/build_test/bin/test_ctx")
set_tests_properties([=[test_ctx]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;10;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_create]=] "/home/rizki/Projects/numc/build_test/bin/test_create")
set_tests_properties([=[test_create]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;11;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_properties]=] "/home/rizki/Projects/numc/build_test/bin/test_properties")
set_tests_properties([=[test_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;12;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_zeros]=] "/home/rizki/Projects/numc/build_test/bin/test_zeros")
set_tests_properties([=[test_zeros]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;13;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_fill]=] "/home/rizki/Projects/numc/build_test/bin/test_fill")
set_tests_properties([=[test_fill]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;14;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_write]=] "/home/rizki/Projects/numc/build_test/bin/test_write")
set_tests_properties([=[test_write]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;15;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_copy]=] "/home/rizki/Projects/numc/build_test/bin/test_copy")
set_tests_properties([=[test_copy]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;16;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_contiguous]=] "/home/rizki/Projects/numc/build_test/bin/test_contiguous")
set_tests_properties([=[test_contiguous]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;17;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_reshape]=] "/home/rizki/Projects/numc/build_test/bin/test_reshape")
set_tests_properties([=[test_reshape]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;18;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_transpose]=] "/home/rizki/Projects/numc/build_test/bin/test_transpose")
set_tests_properties([=[test_transpose]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;19;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_slice]=] "/home/rizki/Projects/numc/build_test/bin/test_slice")
set_tests_properties([=[test_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;20;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_print]=] "/home/rizki/Projects/numc/build_test/bin/test_print")
set_tests_properties([=[test_print]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;21;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_error]=] "/home/rizki/Projects/numc/build_test/bin/test_error")
set_tests_properties([=[test_error]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;22;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_add]=] "/home/rizki/Projects/numc/build_test/bin/test_add")
set_tests_properties([=[test_add]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;25;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_sub]=] "/home/rizki/Projects/numc/build_test/bin/test_sub")
set_tests_properties([=[test_sub]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;26;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_mul]=] "/home/rizki/Projects/numc/build_test/bin/test_mul")
set_tests_properties([=[test_mul]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;27;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_div]=] "/home/rizki/Projects/numc/build_test/bin/test_div")
set_tests_properties([=[test_div]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;28;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_scalar]=] "/home/rizki/Projects/numc/build_test/bin/test_scalar")
set_tests_properties([=[test_scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;29;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_neg]=] "/home/rizki/Projects/numc/build_test/bin/test_neg")
set_tests_properties([=[test_neg]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;30;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_abs]=] "/home/rizki/Projects/numc/build_test/bin/test_abs")
set_tests_properties([=[test_abs]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;31;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_log]=] "/home/rizki/Projects/numc/build_test/bin/test_log")
set_tests_properties([=[test_log]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;32;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_exp]=] "/home/rizki/Projects/numc/build_test/bin/test_exp")
set_tests_properties([=[test_exp]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;33;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_sqrt]=] "/home/rizki/Projects/numc/build_test/bin/test_sqrt")
set_tests_properties([=[test_sqrt]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;34;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_pow]=] "/home/rizki/Projects/numc/build_test/bin/test_pow")
set_tests_properties([=[test_pow]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;35;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_clip]=] "/home/rizki/Projects/numc/build_test/bin/test_clip")
set_tests_properties([=[test_clip]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;36;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_broadcast]=] "/home/rizki/Projects/numc/build_test/bin/test_broadcast")
set_tests_properties([=[test_broadcast]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;37;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_comparison]=] "/home/rizki/Projects/numc/build_test/bin/test_comparison")
set_tests_properties([=[test_comparison]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;38;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_where]=] "/home/rizki/Projects/numc/build_test/bin/test_where")
set_tests_properties([=[test_where]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;39;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_sum]=] "/home/rizki/Projects/numc/build_test/bin/test_sum")
set_tests_properties([=[test_sum]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;42;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_mean]=] "/home/rizki/Projects/numc/build_test/bin/test_mean")
set_tests_properties([=[test_mean]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;43;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_max]=] "/home/rizki/Projects/numc/build_test/bin/test_max")
set_tests_properties([=[test_max]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;44;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_min]=] "/home/rizki/Projects/numc/build_test/bin/test_min")
set_tests_properties([=[test_min]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;45;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_argmax]=] "/home/rizki/Projects/numc/build_test/bin/test_argmax")
set_tests_properties([=[test_argmax]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;46;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_argmin]=] "/home/rizki/Projects/numc/build_test/bin/test_argmin")
set_tests_properties([=[test_argmin]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;47;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_matmul_naive]=] "/home/rizki/Projects/numc/build_test/bin/test_matmul_naive")
set_tests_properties([=[test_matmul_naive]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;50;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_rand]=] "/home/rizki/Projects/numc/build_test/bin/test_rand")
set_tests_properties([=[test_rand]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;53;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_randn]=] "/home/rizki/Projects/numc/build_test/bin/test_randn")
set_tests_properties([=[test_randn]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;54;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_random_init]=] "/home/rizki/Projects/numc/build_test/bin/test_random_init")
set_tests_properties([=[test_random_init]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;55;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_random_he]=] "/home/rizki/Projects/numc/build_test/bin/test_random_he")
set_tests_properties([=[test_random_he]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;56;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
add_test([=[test_random_xavier]=] "/home/rizki/Projects/numc/build_test/bin/test_random_xavier")
set_tests_properties([=[test_random_xavier]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/rizki/Projects/numc/tests/CMakeLists.txt;6;add_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;57;numc_test;/home/rizki/Projects/numc/tests/CMakeLists.txt;0;")
